### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Chienenn**
老師您好 我是芊芃
這是本週的作業，再麻煩您  謝謝～

http://3.106.73.167:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout exceeds screen width in small devices.

Screenshot 2023-09-09 190859

**Comment by Chienenn** [comment]
這是修正後的作業 再麻煩老師了 謝謝
http://3.106.73.167:3000/

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull reques so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
